name: trucktalk
description: Voice translator for drivers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.5
  http: ^1.1.0
  in_app_purchase: ^3.1.11
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
